using HotelManagementSystem.Domain.Factory;
using HotelManagementSystem.Domain.Models;

namespace HotelManagementSystem.Contracts;

public interface IManagerService
{
    /// <summary>
    /// A method to retrieve the total revenue being generated by all rooms
    /// </summary>
    /// <returns>
    /// An integer value which is the sum of the "Rent" attribute of each room that are occupied
    /// </returns>
    int ViewRevenue();

    /// <summary>
    /// A method to retrieve the number of rooms that are currently occupied
    /// </summary>
    /// <returns>
    /// An integer value which is the total number of rooms with the "isVacant" attribute set to false
    /// </returns>
    int ViewOccupancy();
    
    /// <summary>
    /// A method to create a room given a factory object
    /// </summary>
    /// <param name="factory">The factory of the room to create</param>
    /// <param name="roomNumber">The room number of the room</param>
    /// <param name="bedCount">The number of beds the room will have</param>
    /// <exception cref="ArgumentNullException">Thrown when the factory is null</exception>
    void CreateRoom(RoomFactory factory, int roomNumber, int bedCount);
    
    /// <summary>
    /// A method to add a User to the system
    /// </summary>
    /// <param name="user">The user object to add to the system</param>
    /// <exception cref="ArgumentNullException">Thrown when the user is null</exception>
    void AddUser(User user);
}